# Generated by Django 2.2.6 on 2019-11-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('semail', models.EmailField(max_length=254)),
                ('scity', models.CharField(max_length=50)),
                ('sbranch', models.CharField(max_length=50)),
                ('spic', models.ImageField(upload_to='')),
            ],
        ),
    ]
