# Generated by Django 2.2.6 on 2019-11-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsinfo', '0002_remove_student_spic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
